version: "2.2"
volumes:
  db-data:
  app-data:

services:
  db:
    image: postgres:15.2-alpine
    hostname: db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: research
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      TESTING: true
    volumes:
      - /usr/src/app/.venv
    command: poetry run pytest tests
